bm2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('omits/', include('omitapp.urls')),
]

omitapp/urls.py
from django.urls import path

app_name = 'omitapp'

from .views import *

urlpatterns=[
    path('main/', main_view, name='main'),
    path('create/', temp_view, name='create')
]

omitapp/models.py
from django.db import models

# Create your models here.

omitapp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect

# Create your views here.
def main_view(request):
    return render(request, 'omitapp/main.html')


import requests
from bs4 import BeautifulSoup
import json

def check_omit(blog_id):
    post_base = 'https://blog.naver.com/PostViewBottomTitleListAsync.nhn?blogId={}&logNo={}&sortDateInMilli={}'
    p_base = 'https://blog.naver.com/{}/{}'
    blog_base = 'https://blog.naver.com/PostList.nhn?blogId={}&categoryNo=0&from=postList'
    
    r = requests.get(blog_base.format(blog_id))
    sp = BeautifulSoup(r.text, 'html.parser')
    logno = sp.select_one('p.url a').attrs['href'].split('/')[-1]
    daty = ''

    post_urls = []
    while True:
        post_r = requests.get(post_base.format(blog_id, logno, daty))
        results = json.loads(post_r.text)
        
        post_urls.extend([p['logNo'] for p in results['postList']])
        
        logno = results['nextIndexLogNo']
        daty = results['nextIndexSortDate']

        if not logno:
            break

    post_is_searching={}
    for post_url in set(post_urls):
        p_r = requests.get(p_base.format(blog_id, post_url))
        sp = BeautifulSoup(p_r.text, 'html.parser')
        src = sp.select_one('iframe').attrs['src']
        iframe_r = requests.get('http://blog.naver.com%s'%src)
        iframe_sp = BeautifulSoup(iframe_r.text, 'html.parser')
        try:
            post_title = iframe_sp.select_one('div#title_1 span').text
        except:
            post_title = iframe_sp.select_one('div.se-title-text span').text

        search_r = requests.get('https://search.naver.com/search.naver?query={}&where=web'.format('"%s"'%post_title))
        search_sp = BeautifulSoup(search_r.text, 'html.parser')
        search_titles = [t.text.strip() for t in search_sp.select('div.total_tit')]
        if post_title in search_titles:
            post_is_searching[post_title] = True
        else:
            post_is_searching[post_title] = False

    return post_is_searching

def temp_view(request):
    blog_id = request.GET.get('bid')
    result = check_omit(blog_id)
    return render(request, 'omitapp/create.html', {'bid': blog_id, 'result':result})

omitapp/templates/omitapp/create.html
{% extends 'base.html' %}

{% block content %}

<div>
    <h3> {{ blog_id }} 누락 검색 결과 </h3>

    {{ result }}
</div>

{% endblock %}

omitapp/templates/omitapp/main.html
{% extends 'base.html' %}

{% block content %}

    <div style="text-align: center; max-width: 500px; margin: 4rem auto;">
        <div class="mb-4">
            <h4>블로그 누락 확인</h4>
        </div>

        <form action="{% url 'omitapp:create' %}" method="GET">
            {% csrf_token %}
            <input type="text" style="width: 500px;" placeholder="블로그명 입력: ex) blog.naver.com/wolfy -> wolfy만 입력" name="bid"/>
            <input type="submit" class="btn btn-dark rounded-pill col-3 mt-4" value="확인">
        </form>
    </div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="ko">

{% include 'head.html' %}

<body style="font-family: 'NanumSquareR';">
    
    {% include 'header.html' %}

    <hr/>

    {% block content %}
    {% endblock %}

    <hr/>
    
    {% include 'footer.html' %}


</body>
</html>

templates/footer.html
<div class="footer">
    <div class="footer-btn">
        <span>공지사항</span> |
        <span>버그 리포트</span> |
        <span>서비스 소개</span> |
        <span>제휴문의</span>
    </div>
    <div style="margin-top: 1rem;">
        <h6 class="main-font">BlogManger2</h6>
    </div>
</div>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Blog Manager 2</title>

    <!-- BootStrap Link -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <!-- Google Fonts Link -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Redressed&display=swap" rel="stylesheet">

    <!-- Google Material Icons -->
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet">

    <!-- Default CSS Link -->
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

    <style>

        @font-face {
            font-family: 'NanumSquareR';
            src: local('NanumSquareR'),
            url("{% static 'fonts/NanumSquareR.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareEB';
            src: local('NanumSquareEB'),
            url("{% static 'fonts/NanumSquareEB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareL';
            src: local('NanumSquareL'),
            url("{% static 'fonts/NanumSquareL.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareB';
            src: local('NanumSquareB'),
            url("{% static 'fonts/NanumSquareB.otf' %}") format("opentype");
        }

        @font-face {
            font-family: 'NanumSquareRoundOTFB';
            src: local('NanumSquareRoundOTFB'),
            url("{% static 'fonts/NanumSquareRoundOTFB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareRoundOTFEB';
            src: local('NanumSquareRoundOTFEB'),
            url("{% static 'fonts/NanumSquareRoundOTFEB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareRoundOTFL';
            src: local('NanumSquareRoundOTFL'),
            url("{% static 'fonts/NanumSquareRoundOTFL.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareRoundOTFR';
            src: local('NanumSquareRoundOTFR'),
            url("{% static 'fonts/NanumSquareRoundOTFR.otf' %}") format("opentype");
        }
    </style>
</head>

templates/header.html
<div class="header">
    <div>
        <h1 class="main-font">Blog Manager 2</h1>
    </div>
    <div class="header-navbar">
        <a href="{% url 'omitapp:main' %}" class="nav-item"><span>포스트 누락 확인</span></a>
        <a href="{% url 'omitapp:main' %}" class="nav-item"><span>Menu2</span></a>
        <a href="{% url 'omitapp:main' %}" class="nav-item"><span>Menu3</span></a>        
    </div>
</div>